use reto_desarrollo_web;


ALTER TABLE REGISTRO_AGUA
ADD REG_AGUA_RECUENTO_COLIFORMES VARCHAR(100),
    REG_AGUA_COLIFORMES_TOTALES VARCHAR(100),
    REG_AGUA_E_COLI VARCHAR(100),
    REG_AGUA_SALMONELLA_SPP VARCHAR(100),
    REG_AGUA_ESTAFILOCOCOS_AUREUS VARCHAR(100),
    REG_AGUA_HONGOS VARCHAR(100),
    REG_AGUA_LEVADURAS VARCHAR(100),
    REG_AGUA_ESTERILIDAD_COMERCIAL VARCHAR(100),
    REG_AGUA_LISTERIA_MONOCYTOGENES VARCHAR(100),
    REG_AGUA_EQUIPOS VARCHAR(200);


ALTER TABLE REGISTRO_ABA
ADD REG_ABA_MICRORO_AEROBIOS VARCHAR(100),
    REG_ABA_RECUENTO_COLIFORMES VARCHAR(100),
    REG_ABA_COLIFORMES_TOTALES VARCHAR(100),
    REG_ABA_PSEUDOMONAS_SPP VARCHAR(100),
    REG_ABA_E_COLI VARCHAR(100),
    REG_ABA_SALMONELLA_SPP VARCHAR(100),
    REG_ABA_ESTAFILOCOCOS_AUREUS VARCHAR(100),
    REG_ABA_HONGOS VARCHAR(100),
    REG_ABA_LEVADURAS VARCHAR(100),
    REG_ABA_ESTERILIDAD_COMERCIAL VARCHAR(100),
    REG_ABA_LISTERIA_MONOCYTOGENES VARCHAR(100),
    REG_ABA_METODOLOGIA_REFERENCIA VARCHAR(200),
    REG_ABA_EQUIPOS VARCHAR(200);





select * from REGISTRO_AGUA;