
create database reto_desarrollo_web;
use reto_desarrollo_web;

CREATE TABLE usuario (
    usu_id INT PRIMARY KEY IDENTITY(1,1),
    usu_nombre NVARCHAR(100) NOT NULL,
    usu_correo NVARCHAR(150) NOT NULL UNIQUE,
    usu_contrasena NVARCHAR(255) NOT NULL,
    usu_rol NVARCHAR(50) NOT NULL
);
drop table if exists registro_agua;

CREATE TABLE REGISTRO_AGUA (
    REG_AGUA_ID INT IDENTITY(1,1) PRIMARY KEY,
    REG_AGUA_REGION_SALUD VARCHAR(100),
    REG_AGUA_DPTO_AREA VARCHAR(100),
    REG_AGUA_TOMADA_POR VARCHAR(100),
    REG_AGUA_NUM_OFICIO VARCHAR(50),
    REG_AGUA_NUM_MUESTRA VARCHAR(50),
    REG_AGUA_ENVIADA_POR VARCHAR(100),
    REG_AGUA_MUESTRA VARCHAR(100),
    REG_AGUA_DIRECCION VARCHAR(200),
    REG_AGUA_CONDICION_MUESTRA VARCHAR(150),
    REG_AGUA_MOTIVO_SOLICITUD VARCHAR(200),
    REG_AGUA_FECHA_TOMA DATE,
    REG_AGUA_FECHA_RECEPCION DATE,
    REG_AGUA_CLORO_RESIDUAL DECIMAL(5,2),
    REG_AGUA_TEMPERATURA_AMBIENTE DECIMAL(5,2),
    REG_AGUA_FECHA_REPORTE DATE,
    REG_AGUA_MICRORO_AEROBIOS VARCHAR(100),
    REG_AGUA_PSEUDOMONAS_SPP VARCHAR(100),
    REG_AGUA_METODOLOGIA_REFERENCIA VARCHAR(200),
    REG_AGUA_OBSERVACIONES VARCHAR(500),
    REG_AGUA_TIPO_COPA VARCHAR(50),
    REG_AGUA_ESTADO VARCHAR(50),
    USU_ID_REGISTRO INT NOT NULL,
    USU_ID_ANALISTA INT,
    USU_ID_EVALUADOR INT,

    CONSTRAINT FK_REG_AGUA_REGISTRO FOREIGN KEY (USU_ID_REGISTRO) REFERENCES usuario(usu_id),
    CONSTRAINT FK_REG_AGUA_ANALISTA FOREIGN KEY (USU_ID_ANALISTA) REFERENCES usuario(usu_id),
    CONSTRAINT FK_REG_AGUA_EVALUADOR FOREIGN KEY (USU_ID_EVALUADOR) REFERENCES usuario(usu_id)
);

CREATE TABLE REGISTRO_ABA (
    REG_ABA_ID INT IDENTITY(1,1) PRIMARY KEY,
    REG_ABA_NUM_OFICIO VARCHAR(50),
    REG_ABA_FECHA_RECIBO DATE,
    REG_ABA_NOMBRE_SOLICITANTE VARCHAR(150),
    REG_ABA_MOTIVO_SOLICITUD VARCHAR(200),
    REG_ABA_TIPO_MUESTRA VARCHAR(100),
    REG_ABA_CONDICION_RECEPCION VARCHAR(150),
    REG_ABA_NUM_MUESTRA VARCHAR(50),
    REG_ABA_NUM_LOTE VARCHAR(50),
    REG_ABA_FECHA_ENTREGA DATE,
    REG_ABA_COLOR VARCHAR(50),
    REG_ABA_OLOR VARCHAR(50),
    REG_ABA_SABOR VARCHAR(50),
    REG_ABA_ASPECTO VARCHAR(100),
    REG_ABA_TEXTURA VARCHAR(100),
    REG_ABA_PESO_NETO DECIMAL(10,2),
    REG_ABA_FECHA_VENC DATE,
    REG_ABA_ACIDEZ DECIMAL(5,2),
    REG_ABA_CLORO_RESIDUAL DECIMAL(5,2),
    REG_ABA_CENIZAS DECIMAL(5,2),
    REG_ABA_CUMARINA VARCHAR(50),
    REG_ABA_CLORURO DECIMAL(5,2),
    REG_ABA_DENSIDAD DECIMAL(6,3),
    REG_ABA_DUREZA VARCHAR(50),
    REG_ABA_EXTRACTO_SECO VARCHAR(50),
    REG_ABA_FECULA VARCHAR(50),
    REG_ABA_GRADO_ALCOHOLICO DECIMAL(5,2),
    REG_ABA_HUMEDAD DECIMAL(5,2),
    REG_ABA_INDICE_REFACCION DECIMAL(6,3),
    REG_ABA_INDICE_ACIDEZ DECIMAL(5,2),
    REG_ABA_INDICE_RANCIDEZ DECIMAL(5,2),
    REG_ABA_MATERIA_GRASA_CUALIT VARCHAR(100),
    REG_ABA_MATERIA_GRASA_CUANTIT DECIMAL(6,2),
    REG_ABA_PH DECIMAL(4,2),
    REG_ABA_PRUEBA_EBER VARCHAR(50),
    REG_ABA_SOLIDOS_TOTALES DECIMAL(6,2),
    REG_ABA_TIEMPO_COCCION VARCHAR(50),
    REG_ABA_OTRAS_DETERMINACIONES VARCHAR(300),
    REG_ABA_REFERENCIA VARCHAR(200),
    REG_ABA_OBSERVACIONES VARCHAR(500),
    REG_ABA_APTO_CONSUMO BIT,
    REG_ABA_ESTADO VARCHAR(50),
    USU_ID_REGISTRO INT NOT NULL,
    USU_ID_ANALISTA INT,
    USU_ID_EVALUADOR INT,

    CONSTRAINT FK_REG_ABA_REGISTRO FOREIGN KEY (USU_ID_REGISTRO) REFERENCES usuario(usu_id),
    CONSTRAINT FK_REG_ABA_ANALISTA FOREIGN KEY (USU_ID_ANALISTA) REFERENCES usuario(usu_id),
    CONSTRAINT FK_REG_ABA_EVALUADOR FOREIGN KEY (USU_ID_EVALUADOR) REFERENCES usuario(usu_id)
);

